name: Build
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Needed to write to GitHub draft release

env:
  NORTHSTAR_VERSION: ${{ github.ref_name }}

jobs:
  build-launcher:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: Configure cmake
        run: cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE:STRING="Release"
      - name: Setup resource file version
        shell: bash
        run: |
          sed -i 's/DEV/${{ env.NORTHSTAR_VERSION }}/g' primedev/primelauncher/resources.rc
          sed -i 's/DEV/${{ env.NORTHSTAR_VERSION }}/g' primedev/resources.rc
          FILEVERSION=$(echo ${{ env.NORTHSTAR_VERSION }} | tr '.' ',' | sed -E 's/-rc[0-9]+//' | tr -d '[:alpha:]')
          sed -i "s/0,0,0,1/${FILEVERSION}/g" primedev/ns_version.h
      - name: Build
        run: cmake --build build/
      - name: Upload launcher build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: northstar-launcher
          path: |
            build/game/*.exe
            build/game/*.dll
            build/game/bin/x64_retail/*.dll
      - name: Upload debug build artifact
        uses: actions/upload-artifact@v3
        with:
          name: launcher-debug-files
          path: |
            build/game/*.pdb
            build/game/bin/x64_retail/*.pdb

  upload-launcher-to-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-launcher
    runs-on: ubuntu-22.04
    steps:
      - name: Download compiled launcher
        uses: actions/download-artifact@v3
        with:
          name: northstar-launcher
          path: northstar-launcher
      - name: Download compiled launcher
        uses: actions/download-artifact@v3
        with:
          name: launcher-debug-files
          path: launcher-debug-files
      - name: Create zip with binaries
        run: |
          cd northstar-launcher
          zip --recurse-paths --quiet ../northstar-launcher.zip *
      - name: Create zip with debug symbols
        run: |
          cd launcher-debug-files
          zip --recurse-paths --quiet ../launcher-debug-files.zip *
      - name: Upload files to release
        uses: softprops/action-gh-release@v1
        with:
          body: ":warning: These are development files! If you want to download Northstar, [go here instead](https://github.com/R2Northstar/Northstar/releases) :warning:"
          draft: false
          files: |
            northstar-launcher.zip
            launcher-debug-files.zip
